#!/bin/bash

echo "YouTube Cookie Generator Helper"
echo "=============================="
echo ""
echo "This script will help you create a cookies.txt file for YouTube downloads."
echo "Follow these steps:"
echo ""
echo "1. Log in to YouTube in your browser"
echo "2. Install a cookie exporter extension:"
echo "   - Chrome: 'Get cookies.txt' or 'EditThisCookie'"
echo "   - Firefox: 'Cookie Quick Manager' or 'Cookie-Editor'"
echo "3. Go to https://www.youtube.com"
echo "4. Use the extension to export cookies to a file named youtube_cookies.txt"
echo "5. Save the file in the same directory as this script"
echo ""
echo "Alternative: Use the yt-dlp cookie extractor:"
echo ""
echo "# For Chrome/Chromium/Edge:"
echo "poetry run yt-dlp --cookies-from-browser chrome > youtube_cookies.txt"
echo ""
echo "# For Firefox:"
echo "poetry run yt-dlp --cookies-from-browser firefox > youtube_cookies.txt"
echo ""
echo "# For Safari:"
echo "poetry run yt-dlp --cookies-from-browser safari > youtube_cookies.txt"
echo ""
echo "After creating youtube_cookies.txt, run the scraper with:"
echo "poetry run python youtube_scraper.py"
echo ""
echo "This should help bypass the 403 Forbidden errors." 